//
//  FilterInvestmentsRouter.swift
//  Teste-iOS-BTG
//
//  Created by Danilo Henrique on 02/02/19.
//  Copyright © 2019 BTG Pactual. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FilterInvestmentsRoutingLogic {
    func routeToPreviousViewController(source: FilterInvestmentsViewController)
}

protocol FilterInvestmentsRouterDelegate: class {
    func applyFilters(_ filters: FilterInvestmentsModels.Response)
}

protocol FilterInvestmentsDataPassing {
    var dataStore: FilterInvestmentsDataStore! { get set }
    var delegate: FilterInvestmentsRouterDelegate? { get set }
}

class FilterInvestmentsRouter: NSObject, FilterInvestmentsDataPassing, FilterInvestmentsRoutingLogic {
    
    var delegate: FilterInvestmentsRouterDelegate?
    var dataStore: FilterInvestmentsDataStore!
    weak var viewController: FilterInvestmentsViewController?

    func routeToPreviousViewController(source: FilterInvestmentsViewController) {
        delegate?.applyFilters(source.responses)
        source.dismiss(animated: true, completion: nil)
    }
}
