//
//  FundsInvestmentsPresenter.swift
//  Teste-iOS-BTG
//
//  Created by Danilo Henrique on 30/01/19.
//  Copyright © 2019 BTG Pactual. All rights reserved.
//
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundsInvestmentsPresentationLogic
{
    func presentSomething(response: FundsInvestments.Something.Response)
}

class FundsInvestmentsPresenter: FundsInvestmentsPresentationLogic
{
    weak var viewController: FundsInvestmentsDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: FundsInvestments.Something.Response)
    {
        let viewModel = FundsInvestments.Something.ViewModel()
        viewController?.displayFetchedFunds(viewModel: viewModel)
    }
}
