//
//  FundsInvestmentWorker.swift
//  Teste-iOS-BTG
//
//  Created by Danilo Henrique on 30/01/19.
//  Copyright © 2019 BTG Pactual. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation
import Moya

typealias responseHandler = (_ response: FundsInvestments.FetchFunds.Response) -> Void

class FundsInvestmentsWorker {
    
    func fetchFunds(request: FundsInvestments.FetchFunds.Request, completion: @escaping(responseHandler)) {
        
        let ApiManager = MoyaProvider<FundsServiceAPI>()
        
        ApiManager.request(.fundsList) { (result) in
            switch result {
            case .success(let value):
                do {
                    let funds = try value.map([FundModel].self)
                    completion(FundsInvestments.FetchFunds.Response(funds: funds, error: false, message: nil))
                } catch {
                    completion(FundsInvestments.FetchFunds.Response(funds: nil, error: true, message: error.localizedDescription))
                }
            case .failure(let error):
                completion(FundsInvestments.FetchFunds.Response(funds: nil, error: true, message: error.localizedDescription))
            }
        }
    }
    
    func filterFunds(request: FundsInvestments.FetchFunds.Request, funds: [FundModel]) -> FundsInvestments.FetchFunds.Response {
        let filtered = funds.filter({ (fund) -> Bool in
            return fund.product?.localizedCaseInsensitiveContains(request.product ?? "") ?? false
        })
        return FundsInvestments.FetchFunds.Response(funds: filtered, error: false, message: nil)
    }
    
}
