//
//  FundsInvestmentRouter.swift
//  Teste-iOS-BTG
//
//  Created by Danilo Henrique on 30/01/19.
//  Copyright © 2019 BTG Pactual. All rights reserved.
//
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FundsInvestmentsRoutingLogic
{
    func routeToFilterInvestments()
}

protocol FundsInvestmentsDataPassing
{
    var dataStore: FundsInvestmentsDataStore? { get }
}

class FundsInvestmentsRouter: NSObject, FundsInvestmentsRoutingLogic {
    weak var viewController: FundsInvestmentsViewController?
    var dataStore: FundsInvestmentsDataStore?
    
    // MARK: Routing
    
    func routeToFilterInvestments() {
        let storyboard = UIStoryboard(name: "FilterInvestments", bundle: nil)
        let destinationVC = storyboard.instantiateInitialViewController() as! FilterInvestmentsViewController
        navigateToFilterInvestments(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToFilterInvestments(source: FundsInvestmentsViewController, destination: FilterInvestmentsViewController) {
        source.present(destination, animated: true, completion: nil)
      
    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: FundsInvestmentDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
