//
//  FundsInvestmentsInteractor.swift
//  Teste-iOS-BTG
//
//  Created by Danilo Henrique on 30/01/19.
//  Copyright © 2019 BTG Pactual. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundsInvestmentsBusinessLogic
{
    func doSomething(request: FundsInvestments.Something.Request)
}

protocol FundsInvestmentsDataStore
{
    //var name: String { get set }
}

class FundsInvestmentsInteractor: FundsInvestmentsBusinessLogic, FundsInvestmentsDataStore
{
    var presenter: FundsInvestmentsPresentationLogic?
    var worker: FundsInvestmentsWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func doSomething(request: FundsInvestments.Something.Request)
    {
        worker = FundsInvestmentsWorker()
        worker?.doSomeWork()
        
        let response = FundsInvestments.Something.Response()
        presenter?.presentSomething(response: response)
    }
}
