//
//  FundsInvestmentsModels.swift
//  Teste-iOS-BTG
//
//  Created by Danilo Henrique on 30/01/19.
//  Copyright © 2019 BTG Pactual. All rights reserved.
//
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FundsInvestments {
    // MARK: Use cases
    
    enum Funds {
        struct Request {
            let baseUrl: String
            let params: [String: Any]?
        }
        struct Response {
            
        }
        struct ViewModel {
            
        }
    }
}
