//
//  FundsInvestmentRouter.swift
//  Teste-iOS-BTG
//
//  Created by Danilo Henrique on 30/01/19.
//  Copyright © 2019 BTG Pactual. All rights reserved.
//
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FundsInvestmentsRoutingLogic
{
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol FundsInvestmentsDataPassing
{
    var dataStore: FundsInvestmentsDataStore? { get }
}

class FundsInvestmentsRouter: NSObject, FundsInvestmentsRoutingLogic, FundsInvestmentsDataPassing
{
    weak var viewController: FundsInvestmentsViewController?
    var dataStore: FundsInvestmentsDataStore?
    
    // MARK: Routing
    
    //func routeToSomewhere(segue: UIStoryboardSegue?)
    //{
    //  if let segue = segue {
    //    let destinationVC = segue.destination as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //  } else {
    //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //    var destinationDS = destinationVC.router!.dataStore!
    //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //    navigateToSomewhere(source: viewController!, destination: destinationVC)
    //  }
    //}
    
    // MARK: Navigation
    
    //func navigateToSomewhere(source: FundsInvestmentViewController, destination: SomewhereViewController)
    //{
    //  source.show(destination, sender: nil)
    //}
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: FundsInvestmentDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
