//
//  FundsInvestmentsPresenter.swift
//  Teste-iOS-BTG
//
//  Created by Danilo Henrique on 30/01/19.
//  Copyright © 2019 BTG Pactual. All rights reserved.
//
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FundsInvestmentsPresentationLogic
{
    func presentFunds(response: FundsInvestments.FetchFunds.Response)
}

class FundsInvestmentsPresenter: FundsInvestmentsPresentationLogic
{
    weak var viewController: FundsInvestmentsDisplayLogic?
    
    // MARK: Do something
    
    func presentFunds(response: FundsInvestments.FetchFunds.Response) {
        
        guard let responseFunds = response.funds else {
            viewController?.errorFetchingFunds(message: response.message ?? "-")
            return
        }
        
        var displayFunds: [FundsInvestments.FetchFunds.ViewModel.DisplayViewModel] = []
        for fund in responseFunds {
            let displayFund = FundsInvestments.FetchFunds.ViewModel.DisplayViewModel(
                product: fund.product ?? "-",
                categoryDescription: fund.detail?.categoryDescription ?? "-",
                monthProfitability: FormatterUtils.formatPercentage(value: fund.profitability?.month) ?? "-",
                yearProfitability: FormatterUtils.formatPercentage(value: fund.profitability?.year) ?? "-",
                twelveMonthsProfitability:  FormatterUtils.formatPercentage(value: fund.profitability?.twelveMonths) ?? "-",
                minimumInitialInvestment: FormatterUtils.formatNumberToReal(value: fund.minimumInitialInvestment) ?? "-",
                manager: fund.detail?.manager ?? "-",
                begin: FormatterUtils.formatDate(dateString: fund.begin) ?? "-",
                netEquity: FormatterUtils.formatNumberToReal(value: fund.netEquity) ?? "-",
                investimentQuota: fund.detail?.investimentQuota ?? "-",
                riskLevel: RiskModel(rawValue: fund.riskLevel),
                isShowingDetail: false
            )
            
            displayFunds.append(displayFund)
        }
        
        let viewModel = FundsInvestments.FetchFunds.ViewModel(displayFunds: displayFunds)
        viewController?.displayFetchedFunds(viewModel: viewModel)
    }
}
