//
//  FundsInvestmentRouter.swift
//  Teste-iOS-BTG
//
//  Created by Danilo Henrique on 30/01/19.
//  Copyright © 2019 BTG Pactual. All rights reserved.
//
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Presentr

protocol FundsInvestmentsRoutingLogic
{
    func routeToFilterInvestments()
}

protocol FundsInvestmentsDataPassing
{
    var dataStore: FundsInvestmentsDataStore? { get }
}

class FundsInvestmentsRouter: NSObject, FundsInvestmentsRoutingLogic {
    
    weak var viewController: FundsInvestmentsViewController?
    var dataStore: FundsInvestmentsDataStore?
    
    // MARK: Routing
    
    let presentr: Presentr = {
        let width = ModalSize.full
        let height = ModalSize.fluid(percentage: 0.90)
        let center = ModalCenterPosition.customOrigin(origin: CGPoint(x: 0, y: UIScreen.main.bounds.height / 10))
        let customType = PresentationType.custom(width: width, height: height, center: center)

        let presentr = Presentr(presentationType: customType)
        
        presentr.transitionType = .coverVertical
        presentr.dismissTransitionType = .crossDissolve
        presentr.roundCorners = true
        presentr.cornerRadius = 15
        presentr.backgroundOpacity = 0.9
        presentr.dismissOnSwipe = true
        presentr.dismissOnSwipeDirection = .bottom
        return presentr
    }()
    
    func routeToFilterInvestments() {
        let filterTypes: [FilterType] = [
            .risk(types: [.conservative, .moderate, .sophisticated]),
            .category,
            .minimumApplication,
            .rescue,
            .manager,
            .orderBy(orderByTypes: [.maxRescue, .minRescue])
        ]
        let filterComponents = FilterInvestmentsModels.Components.Response(filterTypes: filterTypes)
        
        let storyboard = UIStoryboard(name: "FilterInvestments", bundle: nil)
        let destinationVC = storyboard.instantiateInitialViewController() as! FilterInvestmentsViewController
        destinationVC.router!.dataStore.filterComponents = filterComponents
        destinationVC.router?.delegate = viewController
        navigateToFilterInvestments(source: viewController!, destination: destinationVC)
    }
    
    // MARK: Navigation
    
    func navigateToFilterInvestments(source: FundsInvestmentsViewController, destination: FilterInvestmentsViewController) {
        source.customPresentViewController(presentr, viewController: destination, animated: true, completion: nil)
    }
    
    // MARK: Passing data
    
    //func passDataToSomewhere(source: FundsInvestmentDataStore, destination: inout SomewhereDataStore)
    //{
    //  destination.name = source.name
    //}
}
